# Generated by Django 5.0.1 on 2024-06-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
